version: '3.1'
services:
  api-gtw:
    image: api-gtw:latest
    container_name: api-gtw
    ports:
      - '8080:8080'
    depends_on:
      - auth
    networks:
      - auth

  auth:
    image: auth-svc:latest
    container_name: auth-svc
    depends_on:
      - postgres
      - sms
    networks:
      - auth
      - postgres
      - sms

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres
  sms:
    image: sms-svc:latest
    container_name: sms-svc
    networks:
      - sms

networks:
  auth:
  postgres:
  sms: